### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ibigpapa** [Lispython/pycurl#1]
When attempting to install i get an error using pip or easy_install,   I'm running windows 7 x64 with python 3.3 and using an elevated command prompt.

-----------------------------------------------------Error---------------------------------------------------------
C:\Python33\Scripts>pip install pycurl2
Downloading/unpacking pycurl2
  Downloading pycurl2-7.20.0.tar.gz (133kB): 133kB downloaded
  Running setup.py egg_info for package pycurl2
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "c:\users\me\appdata\local\temp\pip-build\pycurl2\setup.py", li
ne 69
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "c:\users\me\appdata\local\temp\pip-build\pycurl2\setup.py", line 6
9

```
except Exception, e:

                ^
```

SyntaxError: invalid syntax

---

Command python setup.py egg_info failed with error code 1 in c:\users\me\a
ppdata\local\temp\pip-build\pycurl2
Storing complete log in C:\Users\me\pip\pip.log

-----------------------------------------------------------------pip.log------------------------------------------------------------
Downloading/unpacking pycurl2

  Getting page http://pypi.python.org/simple/pycurl2
  URLs to search for versions for pycurl2:
- http://pypi.python.org/simple/pycurl2/
  Getting page http://pycurl2.github.com
  Analyzing links from page http://pypi.python.org/simple/pycurl2/
    Found link http://pypi.python.org/packages/source/p/pycurl2/pycurl2-7.20.0.a1.tar.gz#md5=4fa07b75b44be21abfe633180e5f23f3 (from http://pypi.python.org/simple/pycurl2/), version: 7.20.0.a1
    Found link http://pypi.python.org/packages/source/p/pycurl2/pycurl2-7.20.0.tar.gz#md5=784527d7cdbf77822a096e687ad3a5cc (from http://pypi.python.org/simple/pycurl2/), version: 7.20.0
    Skipping link http://pycurl2.github.com (from http://pypi.python.org/simple/pycurl2/); not a file
    Skipping link http://curl.haxx.se/libcurl/features.html#features (from http://pypi.python.org/simple/pycurl2/); unknown archive format: .html
    Skipping link http://pycurl.sourceforge.net/ (from http://pypi.python.org/simple/pycurl2/); not a file
    Skipping link http://curl.haxx.se/libcurl/features.html#docs (from http://pypi.python.org/simple/pycurl2/); unknown archive format: .html
    Skipping link http://curl.haxx.se/docs/copyright.html (from http://pypi.python.org/simple/pycurl2/); unknown archive format: .html
    Skipping link http://curl.haxx.se/libcurl/features.html#ipv6 (from http://pypi.python.org/simple/pycurl2/); unknown archive format: .html
    Skipping link http://curl.haxx.se/libcurl/features.html#support (from http://pypi.python.org/simple/pycurl2/); unknown archive format: .html
    Skipping link http://curl.haxx.se/libcurl/features.html#fast (from http://pypi.python.org/simple/pycurl2/); unknown archive format: .html
    Skipping link http://curl.haxx.se/libcurl/ (from http://pypi.python.org/simple/pycurl2/); not a file
    Skipping link https://github.com/Lispython/human_curl (from http://pypi.python.org/simple/pycurl2/); not a file
    Skipping link https://secure.travis-ci.org/Lispython/pycurl (from http://pypi.python.org/simple/pycurl2/); not a file
    Skipping link https://github.com/Lispython/pycurl/ (from http://pypi.python.org/simple/pycurl2/); not a file
    Skipping link http://docs.python.org/library/urllib.html (from http://pypi.python.org/simple/pycurl2/); unknown archive format: .html
    Skipping link http://curl.haxx.se/libcurl/using/apps.html (from http://pypi.python.org/simple/pycurl2/); unknown archive format: .html
    Skipping link http://curl.haxx.se/docs/companies.html (from http://pypi.python.org/simple/pycurl2/); unknown archive format: .html
    Skipping link http://peak.telecommunity.com/DevCenter/EasyInstall (from http://pypi.python.org/simple/pycurl2/); not a file
    Skipping link http://curl.haxx.se/libcurl/features.html#thread (from http://pypi.python.org/simple/pycurl2/); unknown archive format: .html
  Analyzing links from page http://pycurl2.github.com
  Using version 7.20.0 (newest of versions: 7.20.0, 7.20.0.a1)
  Downloading from URL http://pypi.python.org/packages/source/p/pycurl2/pycurl2-7.20.0.tar.gz#md5=784527d7cdbf77822a096e687ad3a5cc (from http://pypi.python.org/simple/pycurl2/)
  Running setup.py egg_info for package pycurl2
  
    Traceback (most recent call last):
  
  ```
  File "<string>", line 16, in <module>
  
  File "c:\users\me\appdata\local\temp\pip-build\pycurl2\setup.py", line 69
  
    except Exception, e:
  
                    ^
  ```
  
    SyntaxError: invalid syntax
  
    Complete output from command python setup.py egg_info:
  
    Traceback (most recent call last):
  
  File "<string>", line 16, in <module>
  
  File "c:\users\me\appdata\local\temp\pip-build\pycurl2\setup.py", line 69
  
    except Exception, e:
  
  ```
                ^
  ```

SyntaxError: invalid syntax

---

Command python setup.py egg_info failed with error code 1 in c:\users\me\appdata\local\temp\pip-build\pycurl2

Exception information:
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\pip-1.2.1-py3.3.egg\pip\basecommand.py", line 107, in main
    status = self.run(options, args)
  File "C:\Python33\lib\site-packages\pip-1.2.1-py3.3.egg\pip\commands\install.py", line 256, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python33\lib\site-packages\pip-1.2.1-py3.3.egg\pip\req.py", line 1042, in prepare_files
    req_to_install.run_egg_info()
  File "C:\Python33\lib\site-packages\pip-1.2.1-py3.3.egg\pip\req.py", line 236, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Python33\lib\site-packages\pip-1.2.1-py3.3.egg\pip\util.py", line 612, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in c:\users\me\appdata\local\temp\pip-build\pycurl2

**Comment by Lispython** [comment]
Sorry, but we do not support python 3.3 for the present now.
